# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conversion',
            fields=[
                ('id_conversion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_moneda_buscada', models.CharField(db_column='tipo_moneda_buscada', max_length=3, verbose_name='tipo_moneda_buscada')),
                ('tipo_moneda_encontrada', models.CharField(db_column='tipo_moneda_encontrada', max_length=3, verbose_name='tipo_moneda_encontrada')),
                ('cantidad_encontrada', models.IntegerField(db_column='cantidad_encontrada', verbose_name='cantidad_encontrada')),
            ],
        ),
        migrations.CreateModel(
            name='informacion_moneda',
            fields=[
                ('id_moneda', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_moneda', models.CharField(db_column='tipo_moneda', max_length=3, verbose_name='tipo_moneda')),
                ('nombre', models.CharField(db_column='nombre', max_length=20, verbose_name='nombre')),
                ('pais', models.IntegerField(db_column='pais', verbose_name='pais')),
                ('anio_creacion', models.IntegerField(db_column='anio_creacion', verbose_name='anio_creacion')),
            ],
        ),
        migrations.CreateModel(
            name='sistema',
            fields=[
                ('id_sistema', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_moneda', models.CharField(db_column='tipo_moneda', max_length=3, verbose_name='tipo_moneda')),
                ('cantidad_moneda', models.IntegerField(db_column='cantidad_moneda', verbose_name='cantidad_moneda')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_moneda', models.CharField(db_column='tipo_moneda', max_length=3, verbose_name='tipo_moneda')),
                ('cantidad_moneda', models.IntegerField(db_column='cantidad_moneda', verbose_name='cantidad_moneda')),
            ],
        ),
    ]
