# Generated by Django 2.1.3 on 2018-11-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_divisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='cantidad_encontrada',
            field=models.FloatField(db_column='cantidad_encontrada', verbose_name='cantidad_encontrada'),
        ),
    ]
